CS251/urls.py
from django.contrib import admin
from django.urls import re_path, include
from django.views.generic.base import TemplateView, RedirectView
from django.conf import settings
from django.conf.urls.static import static
from accounts import views

urlpatterns = [
    re_path('admin/', admin.site.urls),
    re_path(r'^accounts/', include('accounts.urls', namespace='accounts')),
    re_path('base/', TemplateView.as_view(template_name='base.html'), name='base'),
    re_path(r'^$', RedirectView.as_view(url='/accounts/', permanent=True)),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import re_path
from accounts import views
from django.conf.urls.static import static
from django.conf import settings


app_name = 'accounts'
urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'register/$', views.register, name='register'),
    re_path(r'login/$', views.login_user, name='login'),
    re_path(r'home/$', views.home, name='home'),
    re_path(r'home_t/$', views.home_t, name='home_t'),
    re_path(r'logout/$', views.logout_user, name='logout'),
    re_path(r'upload/$', views.upload_book,  name='upload_book'),
    re_path(r'upload_t/$', views.upload_book_t,  name='upload_book_t'),
    re_path(r'assigns251/$', views.assigns_251,  name='assigns_251'),
    re_path(r'assigns215/$', views.assigns_215,  name='assigns_215'),
    re_path(r'assigns293/$', views.assigns_293,  name='assigns_293'),
    re_path(r'course_251/$', views.course_251, name='251'),
    re_path(r'course_293/$', views.course_293, name='293'),
    re_path(r'course_215/$', views.course_215, name='215'),
    re_path(r'profile/$', views.profile, name='profile'),
    re_path(r'course/$', views.course, name='course'),
    re_path(r'assignments/$', views.assignments, name='assignments'),
    re_path(r'assignments_s/$', views.assignments, name='assignments_s'),
    re_path(r'vsc/$', views.vsc, name='vsc'),
    re_path(r'new_upload/$', views.new_upload, name='new_upload'),
    re_path(r'new_upload_t/$', views.new_upload_t, name='new_upload_t'),
    re_path(r'view/$', views.view, name='view'),
    re_path(r'courseview/$', views.courseview, name='courseview'),
    re_path(r'grade/(?P<course>.*)$', views.grade, name='grade'),
    re_path(r'submissions/$', views.submissions, name='submissions'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
# Create your models here.

class CreateCourse(models.Model):
	username = models.CharField(max_length=500,default="")
	course = models.CharField(max_length = 5, unique=True, default = "")
	code = models.CharField(max_length = 6, unique=True, default="XXXXXX")
	def _str_(self):
		return self.code

class AddCourse(models.Model):
	username = models.CharField(max_length=500,default="")
	code = models.CharField(max_length = 6,default="")
	def _str_(self):
		return self.code

class UserProfile(models.Model):
	user = models.OneToOneField(User,on_delete=models.CASCADE)
	YEAR_IN_COLLEGE_CHOICES = (
		(1, '1st Year'),
		(2, '2nd Year'),
		(3, '3rd Year'),
		(4, '4th Year'),
	)
	IDENTITY_CHOICE=(
		('teacher','teacher'),
		('student', 'student'),
	)
	courses=models.CharField(max_length=500,default="")
	#courses=models.CharField(choices = Course.COURSE_CHOICE, max_length=100,default="")
	identity=models.CharField(choices=IDENTITY_CHOICE,max_length=100,default="student")
	full_name = models.CharField(max_length = 100)
	year = models.PositiveIntegerField(choices=YEAR_IN_COLLEGE_CHOICES, default=1)
	roll_no = models.CharField(max_length = 8, unique=True)
	#created = models.DateField(editable=False, null=True)

	def _str_(self):
		return self.roll_no

	def save(self):
		if not self.id:
			self.roll_no = self.user.username
			self.created = datetime.date.today()
		super(UserProfile, self).save()

class Book(models.Model):
	Course_choice = (
		('CS251', 'CS251'),
		('CS215', 'CS215'),
		('CS293', 'CS293'),
	)
	username = models.CharField(max_length=500,default="")
	num = models.PositiveIntegerField(default=1)
	course = models.CharField(max_length=5, choices=Course_choice, default='')
	#deadline = models.DateField(default=datetime.now)
	Assignment = models.FileField(upload_to="assignment/", null=True, blank=True)
	extensions = models.CharField(max_length=500,default="")
	zip_tree_directory = models.FileField(upload_to="File_format/", null=True, blank=True)

class Submit(models.Model):
	Course_choice = (
		('CS251', 'CS251'),
		('CS215', 'CS215'),
		('CS293', 'CS293'),
	)
	username = models.CharField(max_length=500,default="")
	num = models.PositiveIntegerField(default=1)
	course = models.CharField(max_length=5, choices=Course_choice, default='')
	Submission = models.FileField(upload_to="submission/", null=True, blank=True)
	def __str__(self):
		return self.num
	
class Assignment(models.Model):
	username = models.CharField(max_length=500,default="")
	num = models.PositiveIntegerField(default=1)
	course = models.CharField(max_length=5, default='')
	Assignment = models.FileField(upload_to="assignment/", null=True, blank=True)
	extensions = models.CharField(max_length=500,default="")
	zip_tree_directory = models.FileField(upload_to="File_format/", null=True, blank=True)

class Solution(models.Model):
	username = models.CharField(max_length=500,default="")
	num = models.PositiveIntegerField(default=1)
	course = models.CharField(max_length=5, default='')
	Submission = models.FileField(upload_to="submission/", null=True, blank=True)

class Grade(models.Model):
	username_t = models.CharField(max_length=500,default="")
	Student = models.CharField(max_length=500,default="")
	num = models.PositiveIntegerField(default=1)
	course = models.CharField(max_length=5, default='')
	marks = models.PositiveIntegerField(default=0)
	FeedBack = models.CharField(max_length=500,default="")

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic
from django.http import HttpResponseRedirect, HttpResponse
from .forms import BookForm, SubmissionForm, UserForm, UserProfileForm, AddCourseForm, CreateCourseForm
from .forms import SolutionForm, AssignmentForm, GradeForm
from .models import Submit, Book, UserProfile, AddCourse, CreateCourse, Assignment, Solution, Grade
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
import csv, os, filecmp
from zipfile import ZipFile
from django.core.exceptions import ObjectDoesNotExist


class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "accounts/signup.html"
#Create your views here.

def index(request):
	if not request.user.is_authenticated:
		return redirect('accounts:login')
	else:
		user_profile = UserProfile.objects.get(user = request.user)
		if user_profile.identity == 'teacher':
			return redirect('accounts:home_t')
		return redirect('accounts:home')

def assigns_251(request):
	user_profile = UserProfile.objects.get(user = request.user)
	if user_profile.identity == 'teacher':
		Submissions = Submit.objects.filter(course = 251)
		return render(request, 'accounts/assign.html',{
            'Submissions': Submissions
        })
	else:
		logout(request)
		return HttpResponseRedirect('/accounts/')

def assigns_215(request):
	user_profile = UserProfile.objects.get(user = request.user)
	if user_profile.identity == 'teacher':
		Submissions = Submit.objects.filter(course = 215)
		return render(request, 'accounts/assign.html',{
            'Submissions': Submissions
        })
	else:
		logout(request)
		return HttpResponseRedirect('/accounts/')

def assigns_293(request):
	user_profile = UserProfile.objects.get(user = request.user)
	if user_profile.identity == 'teacher':
		Submissions = Submit.objects.filter(course = 293)
		return render(request, 'accounts/assign.html',{
            'Submissions': Submissions
        })
	else:
		logout(request)
		return HttpResponseRedirect('/accounts/')

def upload_book(request):
    user_profile = UserProfile.objects.get(user = request.user)
    if request.method == 'POST' and user_profile.identity == 'student':
        form = SubmissionForm(request.POST, request.FILES)
        if form.is_valid:
            question = Book.objects.get(num = request.POST['num'], course = request.POST['course'])
            list = str(question.extensions).split(',')
            f = request.FILES['Submission']
            if f.name.split('.')[1] in list:
                if f.name.split('.') == 'zip':
                    with ZipFile(f, 'r') as zip:
                        zip.extractall()
                        print(zip.namelist(), file=open('output.txt', 'a'))
                    file = question.zip_tree_directory
                    if filecmp.cmp('output.txt', 'media/' + str(file)):
                        form.instance.username = user_profile.user.username
                        form.save()
                        os.remove('output.txt')
                        return redirect('/accounts/home/')
                    else:
                        os.remove('output.txt')
                        form = SubmissionForm()
                        return render(request, 'accounts/upload_book.html', {
                            'form': form,
					        'error_message': 'Invalid Tree Directory'
                        })
                else:
                    form.instance.username = user_profile.user.username
                    form.save()
                    return redirect('/accounts/home/')
            else:
                form = SubmissionForm()
                return render(request, 'accounts/upload_book.html', {
                    'form': form,
					'error_message': 'Invalid file format'
                })
    if user_profile.identity != 'student':
        logout(request)
        return HttpResponseRedirect('/accounts/')
    else:
        form = SubmissionForm()
    return render(request, 'accounts/upload_book.html', {
        'form': form
    })

def new_upload(request):
	user_profile = UserProfile.objects.get(user = request.user)
	if request.method == 'POST' and user_profile.identity == 'student':
		form = SolutionForm(request.POST, request.FILES)
		if form.is_valid:
			form.instance.username = user_profile.user.username
			courses = AddCourse.objects.filter(username = user_profile.user.username)
			for course in courses:
				total = CreateCourse.objects.filter(code = course.code)
				for name in total:
					if name.course == request.POST['course']:
						question = Assignment.objects.get(num = request.POST['num'],course = request.POST['course'])
						list = str(question.extensions).split(',')
						f = request.FILES['Submission']
						if f.name.split('.')[1] in list:
							if f.name.split('.')[1] != 'zip':
								form.save()
								return redirect('/accounts/home/')
							else:
								with ZipFile(f, 'r') as zip:
									zip.extractall()
									print(zip.namelist(), file=open('output.txt', 'a'))
								file = question.zip_tree_directory
								if filecmp.cmp('output.txt', 'media/' + str(file)):
									form.instance.username = user_profile.user.username
									form.save()
									os.remove('output.txt')
									return redirect('/accounts/home/')
								else:
									os.remove('output.txt')
									form = SubmissionForm()
									return render(request, 'accounts/Submit.html',{
										'form': form,
										'error_message': 'Invalid Tree Directory',
									})
						else:
							form = SolutionForm
							return render(request, 'accounts/Submit.html', {
								'form': form,
								'error_message': 'Invalid file format'
							})
	if user_profile.identity != 'student':
		logout(request)
		return HttpResponseRedirect('/accounts/')
	else:
		form = SolutionForm()
	return render(request, 'accounts/Submit.html', {
        'form': form
    })

def new_upload_t(request):
	user_profile = UserProfile.objects.get(user = request.user)
	if request.method == 'POST' and user_profile.identity == 'teacher':
		form = AssignmentForm(request.POST, request.FILES)
		if form.is_valid:
			form.instance.username = user_profile.user.username
			courses = CreateCourse.objects.filter(username = user_profile.user.username)
			for course in courses:
				if course.course == request.POST['course']:
					form.save()
					return redirect('/accounts/home_t/')
	if user_profile.identity != 'teacher':
		logout(request)
		return HttpResponseRedirect('/accounts/')
	else:
		form = AssignmentForm()
	return render(request, 'accounts/Assignment.html', {
        'form': form
    })

def upload_book_t(request):
    user_profile = UserProfile.objects.get(user = request.user)
    if request.method == 'POST' and user_profile.identity == 'teacher':
        form = BookForm(request.POST, request.FILES)
        if form.is_valid:
            form.instance.username = user_profile.user.username
            form.save()
            return redirect('/accounts/home_t/')
    if user_profile.identity != 'teacher':
        logout(request)
        return HttpResponseRedirect('/accounts/')
    else:
        form = BookForm()
    return render(request, 'accounts/upload_book_t.html', {
        'form': form
    })


def register(request):
	if request.user.is_authenticated:
		return render(request, 'accounts/home.html', {'error_message': "You are already registered!!"})
	else:	
		user_form = UserForm(request.POST or None)
		profile_form = UserProfileForm(request.POST or None)
		if request.method == 'POST':
			if user_form.is_valid() and profile_form.is_valid():
				user = user_form.save(commit=False)
				username = user_form.cleaned_data['username']
				password = user_form.cleaned_data['password']
				user.set_password(user.password)
				user.save()
				profile = profile_form.save(commit=False)
				profile.user = user
				profile.save()
				user = authenticate(username=username, password=password)
				if user is not None:
					if user.is_active:
						login(request, user)
						return redirect('accounts:login')
		context = {
			"pform": profile_form,
			"uform": user_form,
		}
		return render(request, 'accounts/register.html', context)

def home(request):
	if not request.user.is_authenticated:
		return redirect('accounts:login')
	user_profile = UserProfile.objects.get(user = request.user)
	if user_profile.identity != 'student':
		logout(request)
		return render(request, 'accounts/login.html')
	else:
		course_form = AddCourseForm(request.POST or None)
		create_courses = CreateCourse.objects.all()
		add_courses = AddCourse.objects.all()
		if request.method == "POST":
			if course_form.is_valid():
				course_form.instance.username = user_profile.user.username
				course_form.save()
				return redirect('accounts:home')
			return render(request, 'accounts/home.html', {'error_message': 'Unmatched Content'})
		context = {
			"form": course_form,
			"create_courses": create_courses,
			"add_courses": add_courses,
		}
		return render(request, 'accounts/home.html', context)	

def login_user(request):
	if request.method == "POST":
		username = request.POST['username']
		password = request.POST['password']
		identity = request.POST['identity']
		user = authenticate(username=username, password=password)
		if user is not None:
			if user.is_active:
				login(request, user)
				try:
					user_profile = UserProfile.objects.get(user=user,identity=identity)
				except ObjectDoesNotExist:
					logout(request)
					return render(request, 'accounts/login.html')
				if user_profile is not None:
					if identity=='student':
						return redirect('accounts:home')
					else:
						return redirect('accounts:home_t')
		else:
			return render(request, 'accounts/login.html', {'error_message': 'Invalid login'})
	logout(request)
	return render(request, 'accounts/login.html')

templates/accounts/Assignment.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Create Assignment</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  </head>
  <body>
<center>
  <h2>Create Assignment</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in form %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <span class="text-danger small">{{ field.errors }}</span>
                                </div>
                                <label class="control-label col-sm-2"style='margin-top: 0.5%;' for="song_title">{{ field.label_tag }}
                                    {{ field }}
                                </label>
                                
                                {% if field.help_text %}
                                <div class="col-sm-offset-2 col-sm-10">
                                    <span class="text-info small">* {{ field.help_text }}</span>
                                </div>
                                {% endif %}
                            </div>
                        {% endfor %}
    <button type='submit' class='btn btn-primary'>Create</button>
  </form>
</center>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</body>
</html>

templates/accounts/assignments.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Assignments</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  </head>
  <body>
{% if user.is_authenticated %}
<table class="table table-bordered border-primary">
    <thead>
        <tr>
          <th scope="col"></b>Qsn.No</th>
          <th scope="col">Course</th>
          <th scope="col">Download</th>
          <th scope="col">Students Submitted</th>
        </tr>
      </thead>
      {% for assign in Assignments %}
        {% if assign.username == user.username %}
          <tbody>
            <tr>
              <th scope="row">{{ assign.num }}</th>
              <td>{{ assign.course }}</td>
              <td><a href="{{ assign.Assignment.url }}" class="btn btn-primary btn-sm">
                Download PDF 
              </a></td>
              <td>
              {% for student in Submissions %}
                {% if student.num == assign.num %}
                  {% if student.course == assign.course %}
                    {{ student.username }} ,
                  {% endif %}
                {% endif %}
              {% endfor %}
              </td>
            </tr>
          </tbody>
        {% endif %}
      {% endfor %}
      {% for assignment in NewAssignments %}
        {% if assignment.username == user.username %}
          <tbody>
            <tr>
              <th scope="row">{{ assignment.num }}</th>
              <td>{{ assignment.course }}</td>
              <td><a href="{{ assignment.Assignment.url }}" class="btn btn-primary btn-sm">
                Download PDF 
              </a></td>
              <td>
              {% for student in NewSubmissions %}
                {% if student.num == assign.num %}
                  {% if student.course == assign.course %}
                    {{ student.username }} ,
                  {% endif %}
                {% endif %}
              {% endfor %}
              </td>
            </tr>
          </tbody>
        {% endif %}
      {% endfor %}
</table>
{% endif %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</body>
</html>

templates/accounts/assignments_s.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Submissions</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  </head>
  <body>
{% if user.is_authenticated %}
<table class="table table-bordered border-primary">
    <thead>
        <tr>
          <th scope="col"></b>Qsn.No</th>
          <th scope="col">Course</th>
          <th scope="col">Download</th>
          <th scope="col">Upload</th>
          <th scope="col">Score</th>
          <th scope="col">FeedBack</th>
          <th scope="col">Respective Teacher</th>
        </tr>
      </thead>
      {% for submit in Submissions %}
        {% if submit.username == user.username %}
          <tbody>
            <tr>
              <th scope="row">{{ submit.num }}</th>
              <td>{{ submit.course }}</td>
              <td><a href="{{ submit.Assignment.url }}" class="btn btn-primary btn-sm">
                Download PDF 
              </a></td>
              <td>
              <a href="./../upload/" class="btn btn-secondary btn-sm">
                Submit
              </a>
            </td>
              <td>
                {% for grade in Grades %}
                {% if grade.course == submit.course %}
                {% if submit.num == grade.num %}
                {{ grade.marks }}
                {% endif %}
                {% endif %}
                {% endfor %}
              </td>
              <td>
                {% for grade in Grades %}
                {% if grade.course == submit.course %}
                {% if submit.num == grade.num %}
                {{ grade.FeedBack }}
                {% endif %}
                {% endif %}
                {% endfor %}
              </td>
              <td>
              {% for teacher in Assignments %}
                {% if teacher.num == submit.num %}
                  {% if teacher.course == submit.course %}
                    {{ teacher.username }} ,
                  {% endif %}
                {% endif %}
              {% endfor %}
              </td>
            </tr>
          </tbody>
        {% endif %}
      {% endfor %}
      {% for submit in NewSubmissions %}
        {% if submit.username == user.username %}
          <tbody>
            <tr>
              <th scope="row">{{ submit.num }}</th>
              <td>{{ submit.course }}</td>
              <td><a href="{{ submit.Assignment.url }}" class="btn btn-primary btn-sm">
                Download PDF 
              </a></td>
              <td>
                <a href="./../new_upload/" class="btn btn-secondary btn-sm">
                  Submit
              </a>
              </td>
              <td>
                {% for grade in Grades %}
                {% if grade.course == submit.course %}
                {% if submit.num == grade.num %}
                {{ grade.marks }}
                {% endif %}
                {% endif %}
                {% endfor %}
              </td>
              <td>
                {% for grade in Grades %}
                {% if grade.course == submit.course %}
                {% if submit.num == grade.num %}
                {{ grade.FeedBack }}
                {% endif %}
                {% endif %}
                {% endfor %}
              </td>
              <td>
              {% for teacher in NewAssignments %}
                {% if teacher.num == submit.num %}
                  {% if teacher.course == submit.course %}
                    {{ teacher.username }} ,
                  {% endif %}
                {% endif %}
              {% endfor %}
              </td>
            </tr>
          </tbody>
        {% endif %}
      {% endfor %}
</table>
{% endif %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</body>
</html>

templates/accounts/create_course.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Create Course</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  </head>
  <body>


  <h2>Create a Course</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type='submit' class='btn btn-primary'>Create</button>
  </form>
  <table class="table" style="margin-top: 6%">
    <thead>
        <tr>
            <th>Teacher</th>
            <th>Course</th>
            <th>Code</th> 
        </tr>
    </thead>
    <tbody>
      {% for course in courses %}
        <tr>
          <td>{{ course.username }}</td>
          <td>{{ course.course }}</td>
          <td>{{ course.code }}</td>
          </tr>
      {% endfor %}
    </tbody>
</table>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</body>
</html>

templates/accounts/login.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Login Interface</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  </head>
  <body>
    
    <section class="vh-100" style="background-color: #9A616D;">
        <div class="container py-5 h-100">
          <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col col-xl-8">
              <div class="card" style="border-radius: 1rem;">
                <div class="row g-0">
                  <div class="col-md-6 col-lg-5 d-none d-md-block">
                    <br> <br>
                    <img src="https://www.theindianwire.com/wp-content/uploads/2019/01/IIT-Bombay.png"
                      alt="login form" class="img-fluid" style="border-radius: 1rem 0 0 1rem; margin-top: 50px;" />
                  </div>
                  <div class="col-md-6 col-lg-7 d-flex align-items-center">
                    <div class="card-body p-4 p-lg-5 text-black">
      
                      <form method="post">
      
                        <div class="d-flex align-items-center mb-3 pb-1">
                          <span class="h1 fw-bold mb-0">Welcome!</span>
                        </div>
      
                        <h5 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">Sign into your account</h5>
                        {% csrf_token %}
                        <div class="form-group">
                          <label class="control-label col-sm-3" for="id_username">
                              Username:
                          </label>
                          <div class="col-sm-10">
                              <input id="id_username" maxlength="30" name="username" type="text">
                          </div>
                          <div class="col-sm-offset-2 col-sm-10">
                              <span class="text-info small">* Use your College roll no.</span>
                          </div>
                      </div>
                    
                      <div class="form-group">
                          <label class="control-label col-sm-3" for="id_password">
                              Password:
                          </label>
                          <div class="col-sm-10">
                              <input id="id_password" maxlength="30" name="password" type="password">
                          </div>
                      </div>
                       <p></p>
                      <div class="form-group">
                          <label class="control-label col-sm-3" for="id_identity">
                              Identity:
                          </label>
                          <div class="col-sm-10">
                              <input id="id_identity" type="radio" name="identity" value="teacher"/>Teacher
                              <input id="id_identity" type="radio" name="identity" value="student" checked="checked"/>Student
                          </div>
                      </div>
                      <p></p>
                        <button class="btn btn-dark btn-lg btn-block" type="submit">    Login</button>
                        
                        
                        <p></p>
                        <p class="mb-5 pb-lg-2" style="color: #393f81;">Don't have an account? <a href="{% url 'accounts:register' %}"
                            style="color: #393f81;"><br>Register here</a></p>
    
                      </form>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>
</html>

templates/accounts/password_reset_confirm.html
{% extends "base.html" %}

{% block title %}Enter new password{% endblock %}

{% block content %}

{% if validlink %}

<h1>Set a new password!</h1>
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Change my password">
</form>

{% else %}

<p>The password reset link was invalid, possibly because it has already been used.  Please request a new password reset.</p>

{% endif %}
{% endblock %}

templates/accounts/password_reset_form.html
{% extends 'base.html' %}

{% block title %}Forgot Your Password?{% endblock %}

{% block content %}
  <h1>Forgot your password?</h1>
  <p>Enter your email address below, and we'll email instructions for setting a new one.</p>

  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Send me instructions!">
  </form>
{% endblock %}